# Generated by Django 2.2.1 on 2019-05-25 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_written', models.DateTimeField(default=django.utils.timezone.now)),
                ('story', models.TextField()),
            ],
        ),
    ]
